module.exports.authService = require('./auth.service')
module.exports.quizService = require('./quiz.service')
module.exports.blogService = require('./blog.service')
module.exports.resourcesService = require('./resources.service')
module.exports.projectService = require('./project.service')
module.exports.questionService = require('./question.service')